DROP PROCEDURE delete_user;

DROP VIEW searchquery;

DROP VIEW mediumdropdown;

DROP VIEW genredropdown;

DROP VIEW selectauthor;

DROP VIEW languagedropdown;

DROP SEQUENCE item_med_seq;

DROP TRIGGER item_medium_aut_incr;

DROP TABLE authored_by CASCADE CONSTRAINTS;

DROP TABLE influenced_by CASCADE CONSTRAINTS;

DROP TABLE borrowed_by CASCADE CONSTRAINTS;

DROP TABLE belongs_to CASCADE CONSTRAINTS;

DROP TABLE phys_book CASCADE CONSTRAINTS;

DROP TABLE audio_book CASCADE CONSTRAINTS;

DROP TABLE lib_item CASCADE CONSTRAINTS;

DROP TABLE lib_section CASCADE CONSTRAINTS;

DROP TABLE author CASCADE CONSTRAINTS;

DROP TABLE user_account CASCADE CONSTRAINTS;

DROP TABLE item_medium CASCADE CONSTRAINTS;

DROP TABLE lib CASCADE CONSTRAINTS;

DROP TABLE lang CASCADE CONSTRAINTS;

DROP TABLE item_genre CASCADE CONSTRAINTS;
